### PR TITLE
Update events-november-2024.md

### PR DESCRIPTION
**Pull request by str4w**
Noticed a minor glitch in the welding event time.  Checked Eventbrite too it is correct there.

### CODE REVIEW

**Comment by kryma-foulab** [comment]
LGTM, thank you for catching this. @cpatulea is there any commit squashing hygiene to adhere to here?

**Comment by cpatulea** [comment]
Individual commits is fine. But maybe check if you want to set author and lastmod in front matter.

**Comment by str4w** [comment]
I don't know where the front matter is to set that.

**Comment by cpatulea** [comment]
kryma knows, he can help

**Pull request merged**
